identifier:
  accessible_labels:
    description: Agency description
    gsa_link_logo: GSA homepage
    identifier: Agency identifier
    links: Important links
    login_gov_logo: Login.gov logo
    usa_gov: U.S. government information and services
  disclaimer: An official website of the [General Services Administration](https://www.gsa.gov)
  links:
    about_agency: About GSA
    accessibility: Accessibility support
    foia: FOIA requests
    ig: Office of the Inspector General
    no_fear_act: No FEAR Act data
    performance: Performance reports
    privacy: Privacy policy
  usa_gov:
    link: Visit USA.gov
    text: Looking for U.S. government information and services?
nav:
  system_status: Login.gov system status
